# Changes here will be overwritten by Copier
_commit: 2e4f7d0
_src_path: gh:34j/pypackage-template
add_me_as_contributor: false
cli_name: ultrasphere-harmonics
copyright_year: '2025'
documentation: true
email: 34j.95a2p@simplelogin.com
full_name: 34j
github_app_installation_ids: 31487150,37771054
github_username: ultrasphere-dev
has_cli: true
initial_commit: false
is_django_package: false
open_source_license: MIT
open_with_editor: true
package_name: ultrasphere_harmonics
project_name: ultrasphere-harmonics
project_short_description: Hyperspherical harmonics in NumPy / PyTorch / JAX
project_slug: ultrasphere-harmonics
run_uv_sync: false
setup_github: false
setup_pre_commit: false

